#### METODOLOGÍA CRISP-DM. PROCESANDO DATOS CON PYTHON. FORMATEANDO DATOS. NORMALIZANDO DATOS. VARIABLES CATEGÓRICAS Y NUMÉRICAS

##### Nombre: Kevin Anthony Tacuri Masca

##### 1. Cree un data frame, elimine las columnas ‘name’, ’ticket’, ‘cabin’, ‘boat’, ‘body’ y ‘home.dest’, contabilice la cantidad de valores únicos por columna e impute a la columna ‘age’ mediante la mediana, a la columna ‘embarked’ mediante la moda y elimine ls filas que contenga valores nulos. Además, convierta a las columnas ‘survived’ y ‘pclass’ a tipo object y, cambie las categorías de ‘pclass’ de 1, 2 y 3 a '1st', '2nd', '3rd' y las categorías de ‘survived’ de 0 y 1 a ‘no’ y ‘yes’

In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [178]:
df = df.drop(columns=['name', 'ticket', 'cabin', 'boat', 'body', 'home.dest'])
df.head()

   pclass  survived     sex      age  sibsp  parch      fare embarked
0       1         1  female  29.0000      0      0  211.3375        S
1       1         1    male   0.9167      1      2  151.5500        S
2       1         0  female   2.0000      1      2  151.5500        S
3       1         0    male  30.0000      1      2  151.5500        S
4       1         0  female  25.0000      1      2  151.5500        S

In [179]:
unicos = df.nunique()
print("Cantidad de valores únicos por columna:\n", unicos)

Cantidad de valores únicos por columna:
 pclass        3
survived      2
sex           2
age          98
sibsp         7
parch         8
fare        281
embarked      3
dtype: int64

In [180]:
df['age'] = df['age'].fillna(df['age'].median())
df['age'].median()

28.0

In [181]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [182]:
df.dropna().head()

   pclass  survived     sex      age  sibsp  parch      fare embarked
0       1         1  female  29.0000      0      0  211.3375        S
1       1         1    male   0.9167      1      2  151.5500        S
2       1         0  female   2.0000      1      2  151.5500        S
3       1         0    male  30.0000      1      2  151.5500        S
4       1         0  female  25.0000      1      2  151.5500        S

In [183]:
df['pclass'] = df['pclass'].astype(object)
df['pclass'] = df['pclass'].replace({1: '1st', 2: '2nd', 3: '3rd'})

df['survived'] = df['survived'].astype(object)
df['survived'] = df['survived'].replace({0: 'No', 1: 'Yes'})

In [184]:
df.head()

  pclass survived     sex      age  sibsp  parch      fare embarked
0    1st      Yes  female  29.0000      0      0  211.3375        S
1    1st      Yes    male   0.9167      1      2  151.5500        S
2    1st       No  female   2.0000      1      2  151.5500        S
3    1st       No    male  30.0000      1      2  151.5500        S
4    1st       No  female  25.0000      1      2  151.5500        S

##### 2. Cree una columna con fechas aleatorias que vayan desde las 00:00 horas del 1 de enero de 2023 hasta las 23:59 horas del 31 de diciembre de 2023. Luego, cree una columna con el formato para fecha 18 July, 2023 06:12 y otra columna con el formato 18/07/2023 06:12 AM, además, extraiga en columnas diferentes el día, día de semana (en inglés), mes y año.

In [185]:
import datetime
import random

inicio = pd.to_datetime('2023-01-01 00:00:00')
fin = pd.to_datetime('2023-12-31 23:59:59')

def fecha_hora_aleatoria(inicio, fin):
    delta = fin - inicio
    int_delta = int(delta.total_seconds())
    aleatorio_segundos = random.randint(0, int_delta)
    return inicio + pd.to_timedelta(aleatorio_segundos, unit='s')

# Generar la columna de fechas y horas aleatorias
df['date_time'] = [fecha_hora_aleatoria(inicio, fin) for _ in range(len(df))]
df.head()

,pclass,survived,sex,age,sibsp,parch,fare,embarked,date_time
0,1st,Yes,female,29.0000,0,0,211.3375,S,2023-07-10 13:59:16
1,1st,Yes,male,0.9167,1,2,151.5500,S,2023-02-02 23:50:37
2,1st,No,female,2.0000,1,2,151.5500,S,2023-06-06 05:59:26
3,1st,No,male,30.0000,1,2,151.5500,S,2023-02-05 05:31:10
4,1st,No,female,25.0000,1,2,151.5500,S,2023-03-27 00:40:03

In [186]:
df["date_time_new1"] = df["date_time"].apply(lambda x: x.strftime("%d-%B-%Y %H:%M:%S"))
df["date_time_new2"] = df["date_time"].apply(lambda x: x.strftime("%d/%m/%Y %I:%M:%S %p"))
df.head()

,pclass,survived,sex,age,sibsp,parch,fare,embarked,date_time,date_time_new1,date_time_new2
0,1st,Yes,female,29.0000,0,0,211.3375,S,2023-07-10 13:59:16,10-July-2023 13:59:16,10/07/2023 01:59:16 PM
1,1st,Yes,male,0.9167,1,2,151.5500,S,2023-02-02 23:50:37,02-February-2023 23:50:37,02/02/2023 11:50:37 PM
2,1st,No,female,2.0000,1,2,151.5500,S,2023-06-06 05:59:26,06-June-2023 05:59:26,06/06/2023 05:59:26 AM
3,1st,No,male,30.0000,1,2,151.5500,S,2023-02-05 05:31:10,05-February-2023 05:31:10,05/02/2023 05:31:10 AM
4,1st,No,female,25.0000,1,2,151.5500,S,2023-03-27 00:40:03,27-March-2023 00:40:03,27/03/2023 12:40:03 AM

In [187]:
df["day"] = df["date_time"].dt.day
df["day_week"] = df["date_time"].dt.day_name()
df["month"] = df["date_time"].dt.month
df["year"] = df["date_time"].dt.year
df.head()

,pclass,survived,sex,age,sibsp,parch,fare,embarked,date_time,date_time_new1,date_time_new2,day,day_week,month,year
0,1st,Yes,female,29.0000,0,0,211.3375,S,2023-07-10 13:59:16,10-July-2023 13:59:16,10/07/2023 01:59:16 PM,10,Monday,7,2023
1,1st,Yes,male,0.9167,1,2,151.5500,S,2023-02-02 23:50:37,02-February-2023 23:50:37,02/02/2023 11:50:37 PM,2,Thursday,2,2023
2,1st,No,female,2.0000,1,2,151.5500,S,2023-06-06 05:59:26,06-June-2023 05:59:26,06/06/2023 05:59:26 AM,6,Tuesday,6,2023
3,1st,No,male,30.0000,1,2,151.5500,S,2023-02-05 05:31:10,05-February-2023 05:31:10,05/02/2023 05:31:10 AM,5,Sunday,2,2023
4,1st,No,female,25.0000,1,2,151.5500,S,2023-03-27 00:40:03,27-March-2023 00:40:03,27/03/2023 12:40:03 AM,27,Monday,3,2023

##### 3. Realice una normalización de las columnas ‘sibsp’ y ‘parch’ mediante un bucle for, asignándoles los nombres ‘sibsp_norm’ y ‘parch_norm’, respectivamente, y eliminando las columnas originales.

In [188]:
columnas_norm =["sibsp","parch"]

for col in columnas_norm:
    max_val = df[col].max()
    min_val = df[col].min()
    
    df[col] = (df[col] - min_val) / (max_val - min_val)

columnas_resultado = {col: f'{col}_norm' for col in columnas_norm}
df = df.rename(columns=columnas_resultado)

df.head()

,pclass,survived,sex,age,sibsp_norm,parch_norm,fare,embarked,date_time,date_time_new1,date_time_new2,day,day_week,month,year
0,1st,Yes,female,29.0000,0.000,0.000000,211.3375,S,2023-07-10 13:59:16,10-July-2023 13:59:16,10/07/2023 01:59:16 PM,10,Monday,7,2023
1,1st,Yes,male,0.9167,0.125,0.222222,151.5500,S,2023-02-02 23:50:37,02-February-2023 23:50:37,02/02/2023 11:50:37 PM,2,Thursday,2,2023
2,1st,No,female,2.0000,0.125,0.222222,151.5500,S,2023-06-06 05:59:26,06-June-2023 05:59:26,06/06/2023 05:59:26 AM,6,Tuesday,6,2023
3,1st,No,male,30.0000,0.125,0.222222,151.5500,S,2023-02-05 05:31:10,05-February-2023 05:31:10,05/02/2023 05:31:10 AM,5,Sunday,2,2023
4,1st,No,female,25.0000,0.125,0.222222,151.5500,S,2023-03-27 00:40:03,27-March-2023 00:40:03,27/03/2023 12:40:03 AM,27,Monday,3,2023

##### 4. Realice una estandarización de la columna ‘age’ mediante un bucle for, asignándoles el nombre ‘age_std’ y eliminando la columna original. Además, realice una dummización de las columnas ‘pclass’ y ‘embarked’ mediante un bucle for, anteponiendo los nombres ‘pclass_type’ y ‘embarked_type’ a cada categoría, respectivamente, y eliminando las columnas originales. Por último, descargue el último data frame obtenido como un archivo CSV.

In [189]:
#Estandarización de la columna 'age'

columnas_est =["age"]

for col in columnas_est:
    mean = df['age'].mean()
    std = df['age'].std(ddof=0)
    
    df[col] = (df[col] - mean) / std

columnas_resultado = {col: f'{col}_std' for col in columnas_est}

df = df.rename(columns=columnas_resultado)
df.head()

,pclass,survived,sex,age_std,sibsp_norm,parch_norm,fare,embarked,date_time,date_time_new1,date_time_new2,day,day_week,month,year
0,1st,Yes,female,-0.039005,0.000,0.000000,211.3375,S,2023-07-10 13:59:16,10-July-2023 13:59:16,10/07/2023 01:59:16 PM,10,Monday,7,2023
1,1st,Yes,male,-2.215952,0.125,0.222222,151.5500,S,2023-02-02 23:50:37,02-February-2023 23:50:37,02/02/2023 11:50:37 PM,2,Thursday,2,2023
2,1st,No,female,-2.131977,0.125,0.222222,151.5500,S,2023-06-06 05:59:26,06-June-2023 05:59:26,06/06/2023 05:59:26 AM,6,Tuesday,6,2023
3,1st,No,male,0.038512,0.125,0.222222,151.5500,S,2023-02-05 05:31:10,05-February-2023 05:31:10,05/02/2023 05:31:10 AM,5,Sunday,2,2023
4,1st,No,female,-0.349075,0.125,0.222222,151.5500,S,2023-03-27 00:40:03,27-March-2023 00:40:03,27/03/2023 12:40:03 AM,27,Monday,3,2023

In [190]:
#Dummización de la columna 'age'

columnas_dum =["pclass","embarked"]

for col in columnas_dum:
    dummy_variable = pd.get_dummies(df[col])

columnas_resultado = {col: f'{col}_type' for col in columnas_dum}

df = df.rename(columns=columnas_resultado)
df.head()

,pclass_type,survived,sex,age_std,sibsp_norm,parch_norm,fare,embarked_type,date_time,date_time_new1,date_time_new2,day,day_week,month,year
0,1st,Yes,female,-0.039005,0.000,0.000000,211.3375,S,2023-07-10 13:59:16,10-July-2023 13:59:16,10/07/2023 01:59:16 PM,10,Monday,7,2023
1,1st,Yes,male,-2.215952,0.125,0.222222,151.5500,S,2023-02-02 23:50:37,02-February-2023 23:50:37,02/02/2023 11:50:37 PM,2,Thursday,2,2023
2,1st,No,female,-2.131977,0.125,0.222222,151.5500,S,2023-06-06 05:59:26,06-June-2023 05:59:26,06/06/2023 05:59:26 AM,6,Tuesday,6,2023
3,1st,No,male,0.038512,0.125,0.222222,151.5500,S,2023-02-05 05:31:10,05-February-2023 05:31:10,05/02/2023 05:31:10 AM,5,Sunday,2,2023
4,1st,No,female,-0.349075,0.125,0.222222,151.5500,S,2023-03-27 00:40:03,27-March-2023 00:40:03,27/03/2023 12:40:03 AM,27,Monday,3,2023

In [192]:
df.to_csv('titanic_data_limpia.csv')